(package
  (name csv)
  (version "0.1.0")
  (license "BSD")
  (authors "Peter Lane")
  (maintainers "Arthur Maciel <arthurmaciel at gmail dot com")
  (description "csv library : functions to read/write CSV data from/to a port")
  (tags "")
  (docs "https://github.com/cyclone-scheme/cyclone-winds/wiki/csv")
  (test "test.scm")
  (dependencies ())
  (test-dependencies ())
  (foreign-dependencies ())
  (library (name (cyclone csv))
    (description "csv library : functions to read/write CSV data from/to a port.")))
